version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql/data:rw

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver